persistence:
  enabled: false
resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi
adminPassword: admin
sidecar:
  dashboards:
    enabled: true
    label: grafana_dashboard
    folder: /tmp/dashboards
datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
    - name: Prometheus
      type: prometheus
      url: http://ec2-operator-prometheus-server.operator-system.svc.cluster.local
      access: proxy
      isDefault: true
    - name: Jaeger
      type: jaeger
      url: http://ec2-operator-jaeger-query.operator-system.svc.cluster.local:16686
      access: proxy
