apiVersion: compute.cloud.com/v1
kind: Ec2Instance
metadata:
  name: web-server-1
  namespace: default

spec:
  instanceType: t3.micro
  amiId: ami-0b6c6ebed2801a5cb  #ubuntu 24
  region: us-east-1
  availabilityZone: us-east-1a

  keyPair: k8s-operator

  securityGroups:
    - sg-04eaef9abc89a4b09

  subnet: subnet-0af73b8bcb11de4e2

  userData: |
    #!/bin/bash
    apt update -y
    apt install -y apache2
    systemctl start apache2
    systemctl enable apache2

  tags:
    Name: k8s-managed-web-server
    ManagedBy: ec2-operator
    Environment: production

  storage:
    rootVolume:
      size: 8
      type: gp3
      encrypted: true
