name: CI Workflows

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  lint-and-test:
    name: Lint & Test Go Code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Build React Frontend (required for go embed)
      working-directory: ./web
      run: npm install && npm run build

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.25'

    - name: Install dependencies
      run: go mod download

    - name: Run Tests
      run: make test

    # To run golangci-lint
    - name: Run golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v2.7.2
        args: --timeout=5m

  web-build:
    name: Build React Frontend
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Dependencies
      working-directory: ./web
      run: npm install

    - name: Lint TS/TSX
      working-directory: ./web
      run: npm run lint

    - name: Build Web
      working-directory: ./web
      run: npm run build
